---
- name: create users using a loop
  hosts: nodes
  vars_files:
    - vars/secret.yml
  tasks:
  - name: create users
    user:
      name: "{{ item.name }}"
      create_home: yes
      comment: '{{ item.name }}@example.com'
      state: present
      password: "{{ item.password | password_hash('sha512') }}"
      update_password: on_create
    no_log: True
    loop:
      - name: Alice
        password: "{{ users.alice_pwhash }}"
      - name: Bob
        password: "{{ users.bob_pwhash }}"
      - name: Carol
        password: "{{ users.carol_pwhash }}"
...
