---
- name: Starting the web server
  hosts: nodes
  remote_user: ansible

  tasks:
  - name: Install httpd
    package: name=httpd

  - name: Create index.html
    copy:
      content: "Welcome to my web server"
      dest: "/var/www/html/index.html"

  - name: Start service httpd
    service:
      name: httpd
      state: started

  - name: Start service firewalld
    service:
      name: firewalld
      state: started

  - name: Open http port
    firewalld:
      service: http
      permanent: true
      state: enabled
  
  - name: Restart service firewalld
    service:
      name: firewalld
      state: restarted
...
