---
- name: Edditing grub files
  hosts: nodes
  remote_user: ansible

  tasks:
  - name: Eddit grub net.ifnames
    lineinfile:
      state: present
      dest: /etc/default/grub
      backrefs: yes
      regexp: '^(GRUB_CMDLINE_LINUX=(?:(?![" ]{{ option | regex_escape }}=).)*)(?:[" ]{{ option | regex_escape }}=\S+)?(.*")$'
      line: '\1 {{ option }}={{ value }}\2'
    vars:
      option: net.ifnames
      value: 0

  - name: Eddit grub biosdevname
    lineinfile:
      state: present
      dest: /etc/default/grub
      backrefs: yes    
      regexp: '^(GRUB_CMDLINE_LINUX=(?:(?![" ]{{ option | regex_escape }}=).)*)(?:[" ]{{ option | regex_escape }}=\S+)?(.*")$'
      line: '\1 {{ option }}={{ value }}\2'
    vars:
      option: biosdevname
      value: 0

  - name: Write grub configuration file
    command: grub2-mkconfig -o /etc/default/grub.cfg
  #   when: (grub_net_ifnames.changed) or (grub_biosdevname.changed)
...
