---
# vars file for install_httpd

services:
  ftp_service: vsftpd
  fw: firewalld

config:
  anonymous_enable: "YES"
  local_enable: "NO"
  anon_upload_enable: "YES"
  anon_mkdir_write_enable: "YES"
  allow_writeable_chroot: "YES"
  anon_root: "/var/ftp"
  no_anon_password: "YES"
  hide_ids: "YES"
  pasv_min_port: 40000
  pasv_max_port: 50000